{{- if and .Values.database.auth.externalSecret.enabled (not .Values.database.auth.existingSecret.name) (not (eq .Values.database.type "external")) -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "romm.fullname" . }}-db
  labels:
    {{- include "romm.mariadb.labels" . | nindent 4 }}
spec:
  secretStoreRef: {{- .Values.database.auth.externalSecret.secretStoreRef | toYaml | nindent 4 }}
  target:
    name: {{ include "romm.fullname" . }}-db
  data:
    - secretKey: password
      remoteRef:
        key: {{ required "database.auth.externalSecret.remoteKey is required when externalSecret is enabled" .Values.database.auth.externalSecret.remoteKey | quote }}
{{- end }}
{{- if and (or (eq .Values.database.type "embedded") (eq .Values.database.type "operator")) .Values.database.auth.rootExternalSecret.enabled (not .Values.database.auth.rootExistingSecret.name) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "romm.fullname" . }}-db-root
  labels:
    {{- include "romm.mariadb.labels" . | nindent 4 }}
spec:
  secretStoreRef: {{- .Values.database.auth.rootExternalSecret.secretStoreRef | toYaml | nindent 4 }}
  target:
    name: {{ include "romm.fullname" . }}-db-root
  data:
    - secretKey: password
      remoteRef:
        key: {{ required "database.auth.rootExternalSecret.remoteKey is required when rootExternalSecret is enabled" .Values.database.auth.rootExternalSecret.remoteKey | quote }}
{{- end }}
