{{- if eq .Values.database.type "operator" -}}
{{- $defaults := dict
  "rootPasswordSecretKeyRef" (dict
    "name" (include "romm.database.rootPasswordSecretName" .)
    "key" (include "romm.database.rootPasswordSecretKey" .))
  "username" .Values.database.connection.user
  "passwordSecretKeyRef" (dict
    "name" (include "romm.database.userPasswordSecretName" .)
    "key" (include "romm.database.userPasswordSecretKey" .))
  "database" .Values.database.connection.name
  "port" (.Values.database.connection.port | int)
}}
{{- $spec := mergeOverwrite $defaults (deepCopy .Values.database.operator.spec) }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "romm.mariadb.fullname" . }}
  labels:
    {{- include "romm.mariadb.labels" . | nindent 4 }}
spec:
  {{- toYaml $spec | nindent 2 }}
{{- end }}
