{{- range $name, $cfg := .Values.romm.persistence }}
{{- if and $cfg.enabled (not $cfg.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "romm.fullname" $ }}-{{ $name }}
  labels:
    {{- include "romm.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $cfg.accessModes | nindent 4 }}
  {{- with $cfg.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $cfg.size }}
{{- end }}
{{- end }}
