app:
  name: harbor-pg
  project: infra
  source:
    repoURL: git@github.com:cloudnative-pg/charts.git
    targetRevision: cluster-v0.3.1
    path: charts/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  helm:
    values: |
      cluster:
        instances: 1
        initdb:
          # Harbor's core expects its database to be named "registry" -- the
          # chart's database.external.coreDatabase points at this name.
          database: registry
          owner: harbor
        storage:
          size: 16Gi
          storageClass: ceph-block
        walStorage:
          enabled: true
          size: 2Gi
          storageClass: ceph-block
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: '300m'
            memory: 1Gi
        logLevel: warning
        roles:
          - name: harbor
            ensure: present
            login: true
            superuser: false
        postgresql:
          pg_hba:
            - host all all 10.0.0.0/8 md5
