app:
  name: mcr-newnouns
  project: infra
  source:
    repoURL: git@github.com:Pale-whale/mcr-operator.git
    targetRevision: HEAD
    path: deploy/chart/mcr-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  helm:
    values: |
      clusterName: newnouns
      router:
        enable: false
      proxies:
        velocity:
          motd: Welcome to new nouns
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          service:
            type: LoadBalancer
            loadBalancerIP: 172.17.69.25
      servers:
        hub:
          eula: true
          tags:
            - lobby
          version: '26.2'
          properties:
            difficulty: peaceful
            gamemode: adventure
            force-gamemode: 'true'
            level-name: hub
          whitelist:
            - nouns_lover
            - Nouns_mommy
          ops:
            - nouns_lover
          storage:
            size: 5Gi
            storageClass: ceph-block
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          env:
            - name: RCON_CMDS_STARTUP
              value: |-
                gamerule spawn_mobs false
                gamerule fall_damage false
                gamerule fire_damage false
                gamerule drowning_damage false
                gamerule freeze_damage false
                gamerule pvp false
        main:
          eula: true
          tags:
            - main
          version: '26.2'
          properties:
            difficulty: normal
            gamemode: survival
            force-gamemode: 'true'
            level-name: newnouns
            level-seed: '-3899835130120818196'
          whitelist:
            - nouns_lover
            - Nouns_mommy
          ops:
            - nouns_lover
          storage:
            size: 20Gi
            storageClass: ceph-block
            source:
              server: lobby
              mode: Move
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          bluemap:
            ingress:
              className: traefik
              host: newnouns.palewhale.fr
              annotations:
                external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
                traefik.ingress.kubernetes.io/router.middlewares: traefik-traefik-forward-auth@kubernetescrd
            resources:
              limits:
                cpu: '2'
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 1Gi
