app:
  name: mcr-operator
  project: infra
  source:
    repoURL: git@github.com:Pale-whale/mcr-operator.git
    targetRevision: HEAD
    path: deploy/chart/mcr-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: mcr-operator
  helm:
    values: |
      image:
        repository: oci.palewhale.fr/library/mcr-operator
      imagePullSecrets: []
      replicaCount: 1
      leaderElection: false
      metrics:
        bindAddress: ''
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
